name: Docker Image Publish
on:
  push:
    branches:
      - main
    # paths:  # 仅在指定文件变化时触发（可选）
    #   # - 'ReadMe.md'
    #   - 'core/ver.py'
#   release:
#     types: [published]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # - name: Setup Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: '20.18.3' # 替换为你的项目所需的 Node.js 版本
      # - name: Build Web UI
      #   run: |
      #     cd ./web_ui
      #     chmod +x build.sh
      #     ./build.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to GHCR
        run: echo  ${{secrets.TOKEN}} | docker login ghcr.io -u  ${{github.actor}} --password-stdin
        
     
      - name: Build and Push Multi-platform Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${{github.repository}}:latest \
            --push \
            .